### ISSUE TITLE
CMAKE Error when compiling - enum chroma_subsampling

### ISSUE THREAD

**Issue by agusting** [sony/nmos-cpp#29]
Hi, trying to build in Ubuntu 16.04 from the latest commit I get the following error:
 
> Scanning dependencies of target nmos-cpp-node
> [ 88%] Building CXX object CMakeFiles/nmos-cpp-node.dir/nmos-cpp-node/main.cpp.o
> In file included from /home/ubuntu/Downloads/sony/nmos-cpp/Development/nmos-cpp-node/main.cpp:10:0:
> /home/ubuntu/Downloads/sony/nmos-cpp/Development/nmos/node_resources.h:17:10: error: use of enum ‘chroma_subsampling’ without previous declaration
>      enum chroma_subsampling;
>           ^
> In file included from /home/ubuntu/Downloads/sony/nmos-cpp/Development/nmos-cpp-node/main.cpp:10:0:
> /home/ubuntu/Downloads/sony/nmos-cpp/Development/nmos/node_resources.h:45:343: error: ‘chroma_subsampling’ has not been declared
>  space, const nmos::transfer_characteristic& transfer_characteristic, chroma_subs
>                                                                       ^
> CMakeFiles/nmos-cpp-node.dir/build.make:62: recipe for target 'CMakeFiles/nmos-cpp-node.dir/nmos-cpp-node/main.cpp.o' failed
> make[2]: *** [CMakeFiles/nmos-cpp-node.dir/nmos-cpp-node/main.cpp.o] Error 1
> CMakeFiles/Makefile2:222: recipe for target 'CMakeFiles/nmos-cpp-node.dir/all' failed
> make[1]: *** [CMakeFiles/nmos-cpp-node.dir/all] Error 2
> Makefile:94: recipe for target 'all' failed
> make: *** [all] Error 2

Adding `#include "nmos/components.h` to node_resources.h seems to fix the complie error.

Hope this help.
Agustin.

**Comment by garethsb-sony** [comment]
Ah, apologies, I forgot that forward declaration of enum types is a Microsoft extension. Thanks for the report.

**Comment by garethsb-sony** [comment]
Fixed.
